USE POE_DB;
CREATE TABLE TB_PRODUCTO(
ID_PRODUCTO INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_PRODUCTO VARCHAR(80) NOT NULL,
VALOR_PRODUCTO INT,
CANTIDAD_PRODUCTO INT,
ESTADO CHAR DEFAULT 'A');

SELECT *FROM TB_PRODUCTO
